---
title: "An Introduction to Bayesian Data Analysis"
subtitle: "DataFest 2017"
author: "Mick Cooney <mickcooney@gmail.com>"
date: "2017-11-17"
output:
  html_document:
    toc: true
    number_sections: true
    fig_caption: yes
    theme: cerulean
  pdf_document: default
---

```{r knit_opts, include = FALSE}
rm(list = ls())

knitr::opts_chunk$set(tidy  = FALSE
                     ,cache = FALSE
                     ,message =  TRUE
                     ,warning =  TRUE
                     ,fig.height =  8
                     ,fig.width  = 11)

library(tidyverse)
library(scales)
library(rstan)
library(bayesplot)
library(cowplot)
library(insuranceData)
library(rstanarm)

options(width = 80L
       ,warn  = 1
       ,mc.cores = parallel::detectCores()
        )

rstan_options(auto_write = TRUE)
theme_set(theme_cowplot())

set.seed(42)
stan_seed <- 42
```



# Insurance Claims

```{r auto_insurance_loss, echo=TRUE}
data(AutoBi)

claims_tbl <- AutoBi
names(claims_tbl) <- claims_tbl %>% names %>% tolower

claims_tbl <- claims_tbl %>%
    mutate(lawyer   = (attorney == 1)
          ,male     = (clmsex   == 1)
          ,married  = (marital  == 1)
          ,seatbelt = (seatbelt == 1)
          ,age      = clmage
          ,insured  = (clminsur == 1)
          ,log_loss = log(loss)
           ) %>%
    filter(complete.cases(.))

model_stanlm <- stan_lm(log_loss ~ lawyer + seatbelt + male + insured + age
                       ,data   = claims_tbl
                       ,prior  = R2(location = 0.8)
                       )
```



# The 8-Schools Problem

```{r create_8_schools, echo=TRUE}
eight_schools_tbl <- tribble(
     ~school, ~effect_mu, ~effect_se
    ,    "A",         25,         15  
    ,    "B",          8,         10  
    ,    "C",         -3,         16  
    ,    "D",          7,         11  
    ,    "E",         -1,          9  
    ,    "F",          1,         11  
    ,    "G",         18,         10  
    ,    "H",         12,         18  
)

ggplot(eight_schools_tbl) +
    geom_errorbar(aes(x = school, ymin = effect_mu - 2 * effect_se, ymax = effect_mu + 2 * effect_se), width = 0) +
    geom_point(aes(x = school, y = effect_mu)) +
    xlab("School") +
    ylab("Effect")
```

## Centred Parameterisation

```{r create_stan_data, echo=TRUE}
standata_lst <- list(
    J     = eight_schools_tbl %>% nrow
   ,y     = eight_schools_tbl$effect_mu
   ,sigma = eight_schools_tbl$effect_se
)
```

```{r create_8_schools_cp, echo=TRUE}
stan_cp_model <- stan_model('eight_schools_cp.stan')

stan_cp_stanfit <- sampling(
    stan_cp_model
   ,data   = standata_lst
   ,iter   = 500
   ,chains = 8
   ,seed   = stan_seed
)

traceplot(stan_cp_stanfit)

plot(stan_cp_stanfit)

cp_np <- stan_cp_stanfit %>% nuts_params

mcmc_parcoord(stan_cp_stanfit %>% as.array, np = cp_np, alpha = 0.05)
```


## Non-Centred Parameterisation

```{r create_8_schools_ncp, echo=TRUE}
stan_ncp_model <- stan_model('eight_schools_ncp.stan')

stan_ncp_stanfit <- sampling(
    stan_ncp_model
   ,data   = standata_lst
   ,iter   = 500
   ,chains = 8
   ,seed   = stan_seed
)

traceplot(stan_ncp_stanfit, pars = c('mu','tau','theta_tilde','theta'))

plot(stan_ncp_stanfit, pars = c('mu','tau','theta_tilde','theta'))

ncp_np <- stan_ncp_stanfit %>% nuts_params

mcmc_parcoord(stan_ncp_stanfit %>% as.array, np = ncp_np, alpha = 0.05)
```



# Thank You


\

mickcooney@gmail.com

\

https://github.com/kaybenleroll/dublin_r_workshops
