---
title: "Calculate Bond Portfolio Cashflows"
author: "Mick Cooney"
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
output:
  rmdformats::readthedown:
    toc_depth: 3
    use_bookdown: TRUE
    code_folding: hide
    fig_caption: TRUE

  html_document:
    fig_caption: yes
    theme: spacelab #sandstone #spacelab #flatly
    highlight: pygments
    number_sections: TRUE
    toc: TRUE
    toc_depth: 3
    toc_float:
      smooth_scroll: FALSE

  pdf_document: default
---


```{r import_libraries, echo=FALSE, message=FALSE}
library(conflicted)
library(tidyverse)
library(scales)
library(cowplot)
library(magrittr)
library(rlang)
library(stringr)
library(glue)
library(purrr)
library(furrr)
library(DT)
library(lubridate)


source("lib_utils.R")

conflict_lst <- resolve_conflicts(
  c("magrittr", "rlang", "dplyr", "readr", "purrr", "ggplot2", "DT")
  )


knitr::opts_chunk$set(
  tidy       = FALSE,
  cache      = FALSE,
  warning    = FALSE,
  message    = FALSE,
  fig.height =     8,
  fig.width  =    11
  )

options(
  width = 80L,
  warn  = 1,
  mc.cores = parallel::detectCores()
  )

theme_set(theme_cowplot())

set.seed(42)

plan(multisession)
```


# Load Data

We first want to load our datasets and prepare them for some simple association
rules mining.

## Load Portfolio Data

We load a first example of our portfolio, containing the basic information we
need to properly account for cashflows.

```{r load_input_data, echo=TRUE}
portfolio_cols <- cols(
  issuer        = col_character(),
  currency      = col_character(),
  coupon        = col_number(),
  issued_date   = col_date(format = "%Y-%m-%d"),
  maturity_date = col_date(format = "%Y-%m-%d"),
  price         = col_number(),
  position      = col_integer()
  )

first_portfolio_tbl <- read_csv(
  file      = "data/highyield_bond_portfolio.csv",
  col_types = portfolio_cols
  )

first_portfolio_tbl %>% glimpse()
```



# Construct Cashflow Data

```{r create_coupon_payment_dates, echo=TRUE}
create_coupon_payment_dates <- function(init_date, final_date) {
  max_year <- difftime(final_date, init_date, units = "days") %>%
    as.numeric() %>%
    divide_by(183) %>%
    ceiling()
  
  coupon_date_tbl <- (init_date %m+% months(6 * 1:max_year)) %>%
    enframe(name = NULL, value = "cashflow_date") %>%
    filter(cashflow_date <= final_date)
  
  return(coupon_date_tbl)
}
```


```{r calculate_cashflow_data, echo=TRUE}
calculate_cashflow_data <- function(init_date, final_date, position, coupon,
                                    contract_size = 1000) {
  
  par_value      <- position  * contract_size
  coupon_payment <- par_value * coupon * 0.01
  
  coupon_data_tbl <- create_coupon_payment_dates(init_date, final_date) %>%
    mutate(
      cashflow_amt = coupon_payment
      )
  
  final_tbl <- tibble(
    cashflow_date = final_date,
    cashflow_amt  = par_value
    )
  
  cashflow_tbl <- list(coupon_data_tbl, final_tbl) %>%
    bind_rows()
  
  return(cashflow_tbl)
}
```


```{r calculate_portfolio_cashflow_data, echo=TRUE}
calculate_portfolio_cashflow_data <- function(portfolio_tbl, current_date,
                                              id_cols = c("issuer", "currency")) {
  cashflow_tbl <- first_portfolio_tbl %>%
    mutate(
      cash_data = pmap(
        list(
          init_date  = issued_date,
          final_date = maturity_date,
          position   = position,
          coupon     = coupon
          ),
        calculate_cashflow_data,
        contract_size = 1000
        )
      ) %>%
    select(any_of(id_cols), cash_data) %>%
    unnest(cash_data) %>%
    filter(cashflow_date >= current_date) %>%
    arrange(cashflow_date)
  
  return(cashflow_tbl)
}
```


# R Environment
 
```{r show_session_info, echo=TRUE, message=TRUE}
sessioninfo::session_info()
```
